# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hieu Nguyen
tagline:          'My personal blog of tech and life.'
description:      'My personal blog of tech and life.'
url:              https://hieunguyentrung.com/

author:
  name:           'Hieu Nguyen'
  url:            https://hieunguyentrung.com/

paginate:         5
google_analytics: 'UA-91839003-1'
github_username: hieunguyentrung
facebook_username: 'nhieu92'
linkedin_username: 'hieunguyentrung'
contactme: 'mailto:nhieu92@gmail.com'

plugins:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-gist]

github:
  repo:           https://github.com/poole/hyde
